#!/usr/bin/env node

const { join } = require('path');
const { existsSync } = require('fs');
const { execSync } = require('child_process');
const consola = require('consola');

const entrypoint = join(__dirname, 'packages/vindigo-cli/dist/index.js');

if(!existsSync(entrypoint)) {
	consola.info('Missing CLI distribution files, building...');

	try {
		execSync('yarn install');
		execSync('yarn workspace vindigo-config build');
		execSync('yarn workspace vindigo-cli build');
	} catch(err) {
		console.error('Failed to build distribution files');
		throw err;
	}
}

try {
	require(entrypoint);
} catch(err) {
	console.error('Failed to initialize CLI');
	throw err;
}